#    Datos de Inicialización
#    GrupoPago.create([{nombre: 'Semanal'}, {nombre: 'Bisemanal'}, {nombre: 'Quincenal'}, {nombre: 'Mensual'}])
#    Estatus.create([{nombre: 'Activo'}, {nombre: 'Cesante'}, {nombre: 'Vacaciones'}, {nombre: 'Licencia'}])
#    TipoSalario.create([{nombre: 'Mensual'}, {nombre: 'Por Hora'}])
#    TipoEmpleado.create([{nombre: 'Permanente'}, {nombre: 'Eventual'}])
#    Sexo.create([{nombre: 'Femenino'}, {nombre: 'Masculino'}])
#    EstadoCivil.create([{nombre: 'Soltero'}, {nombre: 'Casado'}, {nombre: 'Unido'}, {nombre: 'Divorciado'}])
#    FormaPago.create([{nombre: 'Efectivo'}, {nombre: 'Cheque'}, {nombre: 'ACH'}])
#    Sector.create([{nombre: 'Normal'}, {nombre: 'Construccion'}, {nombre: 'Portuario'}])
#    Departamento.create(codigo: '0000', nombre: 'SIN ASIGNAR', activo: true)
#    CentroCosto.create(codigo: '0000', nombre: 'SIN ASIGNAR', activo: true)
#    Proyecto.create(codigo: '0000', nombre: 'SIN ASIGNAR', activo: true)
#    Cargo.create(departamento_id:1, codigo: '0000', nombre: 'SIN ASIGNAR', activo: true)
#    Seccion.create(codigo: '0000', nombre: 'SIN ASIGNAR', activo: true)
#    Relacion.create([{nombre: 'Hijo'}, {nombre: 'Conyugue'}, {nombre: 'Padre'}, {nombre: 'Hermano'}, {nombre: 'Otro'}])
